name: "oscar_data_transform"
version: "1.0.0"

profile: "oscar_data_profile"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: 
  - "target"
  - "dbt_packages"

seeds:
  oscars_datasets:
    film_identity_overwrite:
      file: "seeds/film_identity_overwrite.csv"
      header: true
      quote: '"'
      escape: '"'
      encoding: "utf-8"
      strict_mode: true

models:
  oscar_data_transform:
    example:
      +materialized: view
    staging:
      +materialized: view
    intermediate: 
      +materialized: table
    mart:
      +materialized: table
