oscar_data_profile:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/kaixuanchin/Code/oscars-datasets/duckdb/oscars_analysis_database.duckdb
    # cloud:
    #   type: motherduck
      # all the configuration for motherduck
